#| ************* | ******************************* |
#| Author:       | Keith H.                        |
#| Date Created: | 07/30/2014                      |
#| Purpose:      | Send simple SMTP email messages |
#|               |                                 |
#| ************* | ******************************* |
#!/usr/bin/env python
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

#This method returns a comma separates string
def listToStr(lst):
    return ','.join(lst)

#send_email
# @EMAIL_MSG - message or body of the 
# @EMAIL_SUBJECT - message subject
# @EMAIL_FROM - from email address
# @EMAIL_RECIPIENTS - to email address(es) in a list
def send_email(EMAIL_MSG,EMAIL_SUBJECT,EMAIL_FROM,EMAIL_RECIPIENTS):
    msgMulti = MIMEMultipart()
    msgMulti['From'] = EMAIL_FROM
    msgMulti['To'] = listToStr(EMAIL_RECIPIENTS)
    msgMulti['Subject'] = EMAIL_SUBJECT
    body = EMAIL_MSG
    msgMulti.attach(MIMEText(body,'plain'))
    msgText = msgMulti.as_string()
    print (EMAIL_SUBJECT)
    
    try:
        #Connect to smtp server
        smtpObj = smtplib.SMTP('***ENTER SMTP IP ADDRESS HERE***')
        #Send the email
        smtpObj.sendmail(EMAIL_FROM, EMAIL_RECIPIENTS, msgText)
        #Close the connection and session.
        smtpObj.quit()
    except SMTPException as e:
        print ("Error: unable to send email :  {e}".format(e=error))

#Main - tests the send_email method
def main():
    send_email("Test email was generated by Python");

#If the script is run by itself then call main
if __name__ == "__main__":
   main()
